export const LOGIN = 'LOGIN'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS'
export const SIGNUP = 'SIGNUP'
export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const EMAIL_SEND = 'EMAIL_SEND'
export const EMAIL_SEND_ERROR = 'EMAIL_SEND_ERROR'

export const VERIFY_CODE = 'VERIFY_CODE'
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const LOGOUT = 'LOGOUT'
export const CLEAR_WHOLE_STATE = 'CLEAR_WHOLE_STATE'
